Add securitas direct custom component brand
home-assistant/brands pull request #1931
Opened 2020-10-13 16:31 UTC by segalion

## Proposed change

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

2020-10-13 16:40 UTC, segalion commented
Finally I could upload correct pixel icon and logo...
Please acept PR. Thanks.

2020-10-14 12:05 UTC, olalid approved these changes

2020-10-14 19:56 UTC, frenck requested changes
So is this Securitas Direct or Versisure?

If it is Verisure, we already have those logos you can use (multiple sizes and qualities): https://github.com/home-assistant/brands/tree/master/core_integrations/verisure

If this is Securitas Direct; Securitas uses different brand images for that.

2020-12-01 12:03 UTC, frenck commented
Quite a long time without response has passed. Closing this PR as stale for now. Feel free to re-open when ready 👍

2020-12-01 12:03 UTC, closed without merging