Create safety_signing
home-assistant/brands pull request #3240
Opened 2022-03-08 03:19 UTC by ts24github

## Proposed change

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

2022-03-08 03:19 UTC, homeassistant commented
Hi @ts24github, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;brands#3240).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-03-08 03:47 UTC, ts24github commented
![logo](https://user-images.githubusercontent.com/101158964/157162430-5e208c50-3ac3-4e69-994c-0343745e0a36.png)
![logo@2x](https://user-images.githubusercontent.com/101158964/157162431-bd0ef3f6-b12f-405c-af9c-362ac72fb59e.png)
![icon](https://user-images.githubusercontent.com/101158964/157162438-3722bfb6-0227-48b4-87a6-babdc158ff20.png)
![icon@2x](https://user-images.githubusercontent.com/101158964/157162440-3148221b-0138-4855-a1c4-8932d9648331.png)

2022-03-08 08:05 UTC, frenck requested changes

2022-03-08 08:05 UTC, frenck commented on custom_integrations/safety_signing~d8472769932447d040563af20b7e54fac54887df
> +
This file doesn't belong here? Please remove it.

2022-03-08 09:59 UTC, frenck commented
Hi there @ts24github 👋 

Could you point me to a resource providing more information about the integration/product/manufacturer of this integration?

../Frenck

2022-03-09 02:46 UTC, ts24github commented
> Hi there @ts24github 👋
> 
> Could you point me to a resource providing more information about the integration/product/manufacturer of this integration?
> 
> ../Frenck

Yes,
-This integration about USB token for KPI.
-Auto control device character via usb token and HSM
through the API connect to my server

2022-03-09 09:44 UTC, frenck commented
Cool, but could you point me to a resource providing more information about the integration/product/manufacturer of this integration?

2022-03-10 01:05 UTC, ts24github commented
> Cool, but could you point me to a resource providing more information about the integration/product/manufacturer of this integration?


Yes of course,
-This is my website : www.safetysigning.vn
-About manufacturer : 
SAFEcert Corp
X-04.77, North Towers Building, Sunrise City, 27 Nguyen Huu Tho, Tan Hung Ward, District 7, Ho Chi Minh City, Vietnam
Phone: (028)-668-23732
Email: info@safecert.com.vn

2022-03-10 07:58 UTC, ts24github commented
> Cool, but could you point me to a resource providing more information about the integration/product/manufacturer of this integration?
Manufacturer Devices by : 
FEITIAN Technologies Co., Ltd
www.ftsafe.com

2022-03-11 12:11 UTC, frenck approved these changes
Alright! thanks, @ts24github 👍

2022-03-11 12:14 UTC, merged