Add Enpal
home-assistant/brands pull request #3539
Opened 2022-07-19 06:11 UTC by Skipperro

## Proposed change

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

2022-08-08 20:25 UTC, killer0071234 approved these changes

2022-08-08 21:32 UTC, frenck requested changes
This integration looks a bit odd. Everything looks like Enpal, but the documentation is about something completely else?

![CleanShot 2022-08-08 at 23 30 24](https://user-images.githubusercontent.com/195327/183518424-c51884f4-8e20-4bf3-b167-af51016f716d.png)

What is the state of this custom integration?

2022-08-09 06:15 UTC, Skipperro commented
@frenck To have a base code structure I've copied my other integration - Ipify. But it is going to be Enpal Integration, I just haven't touched ReadMe yet. I've added logos to this repository even before I started to work on integration itself, because I know it can take a while to get the logos online.

I'm currently working on this integration with support from Enpal Dev Team. It's a bit delayed, because I found missing data for the solar battery in Enpal's database that they need to fix on their side, but rest assured, that the integration will be ready at some point and it will be for Enpal GmbH Solar Installation.

2022-08-09 08:21 UTC, frenck approved these changes
Thanks, @Skipperro 👍

2022-08-09 08:21 UTC, merged