Fluss+ Branding for integration in Home-Assistant Core
home-assistant/brands pull request #5651
Opened 2024-07-10 10:03 UTC by NjeruFluss

## Proposed change

## Type of change

- [x] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: https://github.com/home-assistant/core/pull/121599
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/33655
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/fluss/flussHACS

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

2024-07-10 10:11 UTC, frenck requested changes
There is a CI error, can you please take a look?

../Frenck

2024-07-10 10:20 UTC, NjeruFluss commented
Hi @frenck, I already have the Fluss branding as a custom_integration. Is it necessary to change the domain associated with Fluss to get it pulled into the core_integrations? Or is there another way of keeping the domain the same on both?

2024-07-10 11:25 UTC, frenck commented
If you want to keep a custom integration, I recommend on changing the domain of the custom integration to prevent collision with the core integration you've been submitting.

If you are migrating to core fully, the custom integration one can be removed in this PR.

2024-07-10 19:27 UTC, frenck requested changes

2024-07-10 19:27 UTC, frenck commented on custom_integrations/fluss_pluss/icon.png
This is a rename of the custom integration, which should be done in a separate PR.

2024-07-16 06:51 UTC, frenck requested changes
Seems like something went wrong, as this PR is now an empty pull request:

![CleanShot 2024-07-16 at 08 51 15@2x](https://github.com/user-attachments/assets/ba465e65-94b9-43ed-ba9e-dc15ab50c778)


Can you take a look?

../Frenck

2024-07-17 06:53 UTC, frenck commented
You made this comment on the documentation, which should probably have been placed on this PR

![CleanShot 2024-07-17 at 08 52 36@2x](https://github.com/user-attachments/assets/9f1f2742-479d-42f3-bf46-4313d3156b76)

As for that comment, @NjeruFluss; That is not correct.

There is no `fluss` domain in the `core_integrations` in this repository, which is what this PR should be adding.

2024-09-23 08:05 UTC, closed without merging

2024-09-23 08:05 UTC, frenck commented
Closing PR as the parent PR has been closed.