Add branding for Seymour integration
home-assistant/brands pull request #6109
Opened 2024-11-16 22:14 UTC by johncarey70

## Proposed change

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

2024-11-17 00:33 UTC, klaasnicolaas commented
Missing a link to your custom integration repository.

./Klaas

2024-11-17 15:23 UTC, johncarey70 commented
https://github.com/johncarey70/seymour

2024-11-18 08:10 UTC, frenck requested changes
There seems to be something wrong with both the icon and logo assets provided.

- The icon assets looks blown up. Do we have a higher resolution version available?
- The logo looks like the icon with some transparent space added on the sides.

![CleanShot 2024-11-18 at 09 10 01@2x](https://github.com/user-attachments/assets/95676636-3ffd-42e5-9d44-84e030f81482)

Recommendations:
- Add a higher res icon
- Remove the logo version (we will automatically fall back onto the icon provided).

../Frenck

2024-11-22 07:58 UTC, frenck approved these changes

2024-11-22 07:58 UTC, merged