Add files via upload
home-assistant/brands pull request #6204
Opened 2024-12-11 09:48 UTC by alexanderznamensky

## Proposed change

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [ ] Add a new logo or icon for a custom integration (custom component)
  - [ ] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request: 
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository:

## Checklist

- [ ] The added/replaced image(s) are **PNG**
- [ ] Icon image size is 256x256px (`icon.png`)
- [ ] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [ ] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [ ] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

2024-12-11 10:17 UTC, frenck requested changes
Can you please adjust the PR to have a description, and can you point me to the public repository that provides this custom integration?

Thanks @alexanderznamensky 👍 

../Frenck

2024-12-11 10:25 UTC, alexanderznamensky commented
This is just icon of Tuya brand for custom integration: https://github.com/PlusPlus-ua/ha_tuya_ble, whis was slightly changed and renamed to tuya_local_ble

2025-01-13 10:52 UTC, frenck commented
@alexanderznamensky The domain used in this PR doesn't match the linked integration though:

![CleanShot 2025-01-13 at 11 52 03](https://github.com/user-attachments/assets/119ebb04-e6eb-44e1-bee7-8eeb3bfb4482)

2025-02-07 15:45 UTC, frenck commented
Because there hasn't been any activity on this PR for quite some time now, I've decided to close it for being stale.

Feel free to re-open this PR when you are ready to pick up work on it again 👍

../Frenck

2025-02-07 15:45 UTC, closed without merging