Add Minim custom integration logo and icon
home-assistant/brands pull request #6291
Opened 2024-12-27 11:35 UTC by nidble

## Proposed change

Added Minim logo and icon images

https://github.com/nidble/minim_alarm

## Type of change

- [ ] Add a new logo or icon for a new core integration
- [ ] Add a missing icon or logo for an existing core integration
- [x] Add a new logo or icon for a custom integration (custom component)
  - [x] I've added a link to my custom integration repository in the PR description
  - [ ] I've opened up a PR for my custom integration on the [Home Assistant
    Python wheels repository](https://github.com/home-assistant/wheels-custom-integrations)
- [ ] Replace an existing icon or logo with a higher quality version
- [ ] Replace an existing icon or logo after a branding change
- [ ] Removing an icon or logo

## Additional information

- This PR fixes or closes issue: fixes #
- Link to code base pull request:  https://github.com/nidble/brands
- Link to documentation pull request: 
- Link to integration documentation on our website: 
- Link to custom integration repository: https://github.com/nidble/inim_alarm

## Checklist

- [x] The added/replaced image(s) are **PNG**
- [x] Icon image size is 256x256px (`icon.png`)
- [x] hDPI icon image size is 512x512px for  (`icon@2x.png`)
- [x] Logo image size has min 128px, but max 256px, on the shortest side (`logo.png`)
- [x] hDPI logo image size has min 256px, but max 512px, on the shortest side (`logo@2x.png`)

2025-01-02 11:10 UTC, frenck requested changes
Hi there @nidble 👋 

The provided branding seems to differ from the manufacturer branding:

![CleanShot 2025-01-02 at 12 09 41](https://github.com/user-attachments/assets/61186937-19ff-4504-a530-0df82a3c2885)


Could you please take a look and make sure the branding matches?

Thanks! 👍 

../Frenck

2025-01-02 18:37 UTC, nidble commented
Hello @frenck, yes for Inim integration a set of suitable images was already covered by this PR #5571. However, Inim license is very restrictive, and it prohibits any usage of their logo and image: [general conditions](https://www-inim-biz.translate.goog/it/pagine/condizioni-generali?_x_tr_sl=it&_x_tr_tl=en&_x_tr_hl=it&_x_tr_pto=wapp)
So for getting rid of any license issue/problem I created Minim.

wdyt? Thanks

2025-01-02 20:25 UTC, frenck commented
Unfortunately, we will not accept custom branding creations. The problem with those, is that if a brand is misrepresented often leads to other issues as well.

Integrations, however, do not require branding and function perfectly fine without. So, that leave you with the choice to either update the branding to represent it correctly, or closing the PR and leave the integration without it (as that is fine too).

../Frenck

2025-01-03 10:59 UTC, nidble commented
It sounds good for me! Thank you!

2025-01-03 10:59 UTC, closed without merging